### ISSUE TITLE
[FEATURE] Add button to invert controls for driving backward

### ISSUE THREAD

**Issue by benjaminwp18** [cwruRobotics/rov-24#100]
### Is your feature request related to a problem? Please describe

We need to drive backwards to use the depth cam. It's hard to drive backwards with forward driving controls.

### Describe the solution you'd like

Add a button to the pilot GUI to switch up some of the controls to make driving backwards easier. This should ideally only make changes to nodes running on the surface, but should be far enough downstream that every input method (controller & keyboard) are inverted.

### Describe alternatives you've considered

Possibly use a button on the controller or on the operator GUI instead of/in addition to the pilot GUI button.

**Comment by InvincibleRMC** [comment]
Should probably be attached to the Camera Switch Topic? @benjaminwp18

**Comment by benjaminwp18** [comment]
> Should probably be attached to the Camera Switch Topic? @benjaminwp18 

Is there a chance the pilot would have the depth cam stream up on the switchable widget while driving forward with the front cam?
