### ISSUE TITLE
[FEATURE] Pi Heartbeat PyQt Widget

### ISSUE THREAD

**Issue by benjaminwp18** [cwruRobotics/rov-24#107]
### Is your feature request related to a problem? Please describe

Sometimes the console messages on the surface side from the Pi heartbeat feature go zipping off the screen before I can see them.

### Describe the solution you'd like

Add a widget to the debug GUI that displays current Pi status according to the heartbeat

**Comment by InvincibleRMC** [comment]
Please making the widget blink based on the hertz of the message :)
