### ISSUE TITLE
[FEATURE] Engooden the GUIs

### ISSUE THREAD

**Issue by benjaminwp18** [cwruRobotics/rov-24#115]
### Is your feature request related to a problem? Please describe

Both GUIs are bad

### Describe the solution you'd like

Redesign to be pretty and make final decisions about where cams will go/how many monitors we'll have.

**Comment by NoahMollerstuen** [comment]
Pilot Gui: Will be displayed on vertical monitor. Should have: camera streams, timer widget with no buttons, vehicle state widget? Should not require any mouse interaction.

Operator Gui: will be displayed on laptop screen. Has pretty much everything but camera streams: arm buttons, console, timer, auto tasks, vehicle state widget, flooding indicator, debug tab, ect

Livestream Gui?!?!?!: Secret third display-only gui with camera streams, Cwrubotix logo, and the display version of the camera
