### ISSUE TITLE
[FEATURE] Make sure we can stream our GUI to the MATE people

### ISSUE THREAD

**Issue by benjaminwp18** [cwruRobotics/rov-24#118]
### Is your feature request related to a problem? Please describe

We have to stream a view of our GUI to the judges (?) during competition.

### Describe the solution you'd like

Figure out how to do this. Read the rules. HDMI capture? They have an HDMI cable?

**Comment by NoahMollerstuen** [comment]
Info from the livestream coordinator: `There will be an HDMI cable (Type A standard male) at the product demo station for you to plug into your HDMI splitter (or device)`.

My pitch: Plug the hdmi cable straight into the laptop and treat it as a third independent monitor. Make a third gui with the two camera feeds, our logo and a version of the timer with no start and reset buttons. Investigate making this automatically start in fullscreen on the third monitor.

**Comment by NoahMollerstuen** [comment]
This should include automatically detecting when two external monitors are plugged in and sending the appropriate gui (fullscreen) to each monitor, because it would be difficult to manually drag the appropriate window to the livestream and fullscreen it
