### ISSUE TITLE
[FEATURE] Motor Testing

### ISSUE THREAD

**Issue by InvincibleRMC** [cwruRobotics/rov-24#12]
**Is your feature request related to a problem? Please describe.**
Motor Testing in GUI.

**Describe the solution you'd like**
A new tab in the operator GUI which allows testing of a specific motor speed and direction. Can be based on the QGroundControl one. 

A useful addition would be a config file so we could flip a motor's direction or its number in software.

**Describe alternatives you've considered**
Making mech or hardware mess around with cables.

**Additional context**
I would start with the Pixhawk side because only spinning one motor seems difficult.

**Comment by NoahMollerstuen** [comment]
We can use the manual command mavros message to send the MAV_CMD_DO_MOTOR_TEST command to move the motors in sequence. Then we can use the mavros ParamPush message to change the function of each motor pin

https://mavlink.io/en/messages/common.html#MAV_CMD_DO_MOTOR_TEST
https://wiki.ros.org/mavros/Plugins#param
https://ardupilot.org/copter/docs/parameters.html#servo10-parameters
