### ISSUE TITLE
[BUG] The ethernet cams don't set up their IPs on connection to surface

### ISSUE THREAD

**Issue by benjaminwp18** [cwruRobotics/rov-24#155]
### Describe the bug

Every time we reboot the Pi, we have to go into SpinView to reset the cam IPs.

### To Reproduce

1. Turn on surface laptop
2. Boot robit & connect
3. No cam :(
4. Open spinview & reset IP
5. Reopen GUI
6. Yes cam :/

**Comment by InvincibleRMC** [comment]
@NoahMollerstuen Fixed
