### ISSUE TITLE
[BUG] Camera Streaming Problems

### ISSUE THREAD

**Issue by InvincibleRMC** [cwruRobotics/rov-24#18]
**Describe the bug**
Camera Streams have been freezing/dropping when all cams are running.

**To Reproduce**

1. Run code on pi
2. Run code on surface
3. Look at camera feeds

**Expected behavior**
No freezing or dropping should occur

**Additional context**
Creating some automated method of testing for this to prove that the problem wont occur in the future would be nice.

**Comment by benjaminwp18** [comment]
Test this with both FLIR cams, a USB cam, and the depth cam (if we'll be using it)
