### ISSUE TITLE
[BUG] `manual_control_node.py` is PEP8 noncompliant

### ISSUE THREAD

**Issue by ky28059** [cwruRobotics/rov-24#20]
**Describe the bug**
According to PEP 8 (the official Python style guide, I might add),

<img width="641" alt="image" src="https://github.com/cwruRobotics/rov-24/assets/60120929/bc85f8bf-4bcb-47c0-b2af-69d1cde54a57">

Alas, looking in `manual_control_node.py`, one would find that this **wrong** behavior is perpetuated throughout the file.
https://github.com/cwruRobotics/rov-24/blob/main/src/surface/task_selector/task_selector/manual_control_node.py#L15-L39

**To Reproduce**

1. Go to [`manual_control_node.py`](https://github.com/cwruRobotics/rov-24/blob/main/src/surface/task_selector/task_selector/manual_control_node.py#L15-L39)
2. Look with your eyeballs
3. See error

**Expected behavior**
There should not be extra whitespace to align the variable assignments with each other.

**Additional context**
💯

**Comment by ky28059** [comment]
@InvincibleRMC

**Comment by benjaminwp18** [comment]
good sir
thou art a hooligan
it is hereby the opinion of this quorum that this tenant of PEP8 is, mainly, silly

wontfix

💯
