### ISSUE TITLE
LGPIO for manipulators

### ISSUE THREAD

**Issue by InvincibleRMC** [cwruRobotics/rov-24#5]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated with submodules. If possible we should switch our manipulators' control to use the new lgpio python package.

**Describe the solution you'd like**

Use the lgpio package.

**Describe alternatives you've considered**

**Additional context**

**Comment by InvincibleRMC** [comment]
Manipulators does not work with submodule as of python 3.10 because the submodule we were using has yet to been updated.

**Comment by InvincibleRMC** [comment]
Used smbus2

**Comment by Tazmania40** [comment]
Is this issue complete?

**Comment by benjaminwp18** [comment]
Blocking on new motherboard
